### PR TITLE
Bug: Fixed footer

### PR DESCRIPTION
**Pull request by Meetjain1**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
None

### Description:
This PR enhances the footer section of the website by adding the current copyright year, which is fetched dynamically. This ensures that the copyright year will always be up-to-date without requiring manual updates each year.

#### Changes:
1. **Footer HTML**: Updated the footer to include a placeholder for the copyright year.
2. **JavaScript**: Added a script to fetch the current year dynamically and insert it into the footer.
3. **CSS**: Ensured that the styling of the footer remains consistent with the new dynamic content.

#### Benefits:
- **Automation**: The copyright year updates automatically, reducing maintenance overhead.
- **Accuracy**: Ensures the displayed year is always current, improving the website's professionalism.

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Meetjain1** [comment]
@SiddharthBahuguna please review this pr

**Comment by Meetjain1** [comment]
> @SiddharthBahuguna please review this pr

@SiddharthBahuguna

**Comment by SiddharthBahuguna** [comment]
@Meetjain1 this PR does not add value in the project.

**Comment by Meetjain1** [comment]
> @Meetjain1 this PR does not add value in the project.

why so ?

**Comment by Meetjain1** [comment]
> > @Meetjain1 this PR does not add value in the project.
> 
> why so @SiddharthBahuguna ?

**Comment by Meetjain1** [comment]
@SiddharthBahuguna 

> > > @Meetjain1 this PR does not add value in the project.
> > 
> > 
> > why so @SiddharthBahuguna ?

please review this pr . before gssoc ends . Thanks

**Comment by SiddharthBahuguna** [comment]
I have reviewed it.

**Comment by SiddharthBahuguna** [comment]
@Meetjain1 you have just edited 1 line which was also not required.

This task was also not assigned to you by any of the mentors.

**Pull request closed without merging**
