### PR TITLE
Implement Authentication (Login, Logout, Registration)

### PR DESCRIPTION
**Pull request by anurag6569201**
added all the user authentication and redirection added sigin signup and logout feature......logout  view is thier just need to modify the navbar in next pr i will update the navbar too

### CODE REVIEW

**Comment by anurag6569201** [comment]
@SiddharthBahuguna hey can i add good navbar and also redesign the whole page and also structured the whole code to looks like maintainable code....and also i have a idea to implement user profile where he/she can create thier profile and from admin panel we can manage all the database

**Comment by anurag6569201** [comment]
and also can you send me the logo because according to logo color palette will make website more appealing

**Comment by SiddharthBahuguna** [comment]
please send s.shot of your work.

**Comment by anurag6569201** [comment]
Screenshot 2024-05-13 192339
Screenshot 2024-05-13 192449
thats are the screenshots of signin and signup pages

**Comment by anurag6569201** [comment]
@SiddharthBahuguna please send me logo so that i can work on redesigning the whole project and make it good by frontend as well as backend

**Comment by SiddharthBahuguna** [comment]
send ur email

**Comment by anurag6569201** [comment]
anurag6569201@gmail.com

**Pull request merged**
