### PR TITLE
added password and username instruction, added error messages

### PR DESCRIPTION
**Pull request by rashiranjan22**
Added the instruction for password and username according to already defined constraints in JS file and in settings.py 
Added error messages if the inputs fail to fulfill the constraints
I made a slight change in signup.html file for show buttons , as they were creating problem in registering.
image

### CODE REVIEW

**Comment by anurag6569201** [comment]
nyc work bro

**Comment by SiddharthBahuguna** [comment]
This branch has conflict.Please resolve @rashiranjan22

**Comment by rashiranjan22** [comment]
@SiddharthBahuguna , kindly review

**Comment by SiddharthBahuguna** [comment]
I have merged it.

**Pull request merged**
