### PR TITLE
added read aloud 

### PR DESCRIPTION
**Pull request by rashiranjan22**
## Related Issue
#121 

## Description
added read aloud option so that users can listen to the articles 

## Type of PR

- [X] Feature enhancement

## Screenshots / videos (if applicable)
https://github.com/SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT/assets/117447090/026110e5-daec-4c6b-84a2-be8b77bd48f5

## Checklist:
- [ X I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
I also fixed base.html path specified in index.html and bookmarks.html

### CODE REVIEW

**Comment by SiddharthBahuguna** [comment]
@anurag6569201 Please check.

**Comment by rashiranjan22** [comment]
@SiddharthBahuguna , is something missing ??

**Comment by anurag6569201** [comment]
@rashiranjan22 what us the use of start stop pause

**Comment by rashiranjan22** [comment]
when one click on start button it fetches the article content on the website the url directs to and start reading it
with pause/resume one can pause it and resume it where it was left
stop button stops it completely

**Comment by rashiranjan22** [comment]
@SiddharthBahuguna , please label the PR

**Pull request merged**
