### PR TITLE
added the changes

### LINKED ISSUE #62: Feat:Adding the glow effect for the text input in sign up
### Describe the feature

Better UI

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by YadlaMani**
## Related Issue
# closes #62 

## Description
added the glow effect for input text in sign up and sign in page

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by anurag6569201** [comment]
@YadlaMani present the output result in screenshot

**Comment by YadlaMani** [comment]
image

**Comment by YadlaMani** [comment]
@anurag6569201 check the screen short

**Comment by anurag6569201** [comment]
> @anurag6569201 check the screen short

bro are you serious by adding bootstrap class btn it can be you making such type of pr are you serious....

**Comment by YadlaMani** [comment]
@anurag6569201 i have just done the changes i said and it's working and looks good what's wrong in that

**Comment by YadlaMani** [comment]
i can add more changes if you want different one

**Comment by anurag6569201** [comment]
> @anurag6569201 i have just done the changes i said and it's working and looks good what's wrong in that

the thing is you doing such silly thing after viewing your profile I am expecting to make real contribution by adding new feature which can be remarkable

**Comment by YadlaMani** [comment]
@anurag6569201 i was just doing the thing i mentioned i can do bigger contributions if you have any bigger issues which you can assign me

**Comment by anurag6569201** [comment]
> @anurag6569201 i was just doing the thing i mentioned i can do bigger contributions if you have any bigger issues which you can assign me

findout new feature can be implementable and then raise issue for it if the feature in favor of project admin will assign you

**Comment by YadlaMani** [comment]
@anurag6569201 this project is not my tech stack i can only do front-end contributions

**Comment by SiddharthBahuguna** [comment]
@YadlaMani You can contribute in other ways by suggesting or adding new features to the project that enhance its functionality.
The issue you are currently working on is not a significant task. Please find a more substantial one so that I can assign it to you.

**Comment by YadlaMani** [comment]
@anurag6569201 @SiddharthBahuguna i have added a new issue review it once

**Pull request closed without merging**
