### PR TITLE
added google authentication fixes #74 #154

### LINKED ISSUE #74: Feat: Implement  Google login
### Describe the feature

Allow users to sign in  using their existing Google accounts.
@SiddharthBahuguna ,kingly assign me this issue
### Add ScreenShots

Screenshot (390)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### LINKED ISSUE #154: Feat: Adding Google auth
### Describe the feature

We can add google auth for one click signin so that user can easily signin .

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ankita685**
fixes #154

### CODE REVIEW

**Comment by ankita685** [comment]
@SiddharthBahuguna  please review it once

**Comment by anurag6569201** [comment]
@ankita685 please post a video here for the whole authentication and then for homepage

**Comment by ankita685** [comment]
> @ankita685 please post a video here for the whole authentication and then for homepage


https://github.com/user-attachments/assets/6275d606-2d29-4d30-8946-8c12a10f8508

**Comment by ankita685** [comment]
@anurag6569201 please check this video

**Pull request merged**
