### PR TITLE
feat: added issue btns and respective forms

### PR DESCRIPTION
**Pull request by dakshsinghrathore**
This PR solves the issue #1  , kindly review it and merge.

### CODE REVIEW

**Comment by SiddharthBahuguna** [comment]
What changes you have made.Please explain in detail

**Comment by dakshsinghrathore** [comment]
@SiddharthBahuguna once you merge this PR, you will see something like [this](https://github.com/VanshKing30/FoodiesWeb/issues/new/choose) in your own repo, I hope that explains

**Comment by SiddharthBahuguna** [comment]
I have merged.

**Comment by dakshsinghrathore** [comment]
@SiddharthBahuguna Kindly assign me the issue #1  also add the GSSOC24 label along with level you want to give to this issue.

**Comment by SiddharthBahuguna** [comment]
Ok

**Comment by dakshsinghrathore** [comment]
@SiddharthBahuguna kindly add the gssoc apt labels

**Pull request merged**
